Add basic AWS schemas
DataBiosphere/terra-workspace-manager pull request #1164
Opened 2023-03-22 20:59 UTC by dexamundsen

2023-04-05 14:10 UTC, jmczerk requested changes

2023-04-05 14:36 UTC, jmczerk commented on openapi/src/parts/workspace_cloudcontext.yaml
> +        tenantId:
We also want major version from `Metadata`.

2023-04-05 15:46 UTC, ddietterich reviewed
This is looking good. I have a few questions

2023-04-05 16:37 UTC, zloery commented on service/src/main/java/bio/terra/workspace/service/workspace/flight/WorkspaceFlightMapKeys.java
> +  public static final String SAM_USER = "samUser";
This also looks unused

2023-04-05 19:15 UTC, ddietterich commented on service/src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
> +  public void deleteAwsCloudContext(Workspace workspace, AuthenticatedUserRequest userRequest) {
+1

2023-04-05 19:17 UTC, ddietterich commented on service/src/main/java/bio/terra/workspace/service/workspace/flight/aws/CreateAwsContextFlight.java
> +
We could shortcut this, however, I plan to extend the resource state scheme to workspace+cloudContext, so am biased to keep the pattern. I'd suggest leaving it as is for now. We can re-evaluate when the state stuff is implemented for workspaces.

2023-04-05 19:52 UTC, dexamundsen commented on service/src/main/java/bio/terra/workspace/service/workspace/flight/aws/CreateAwsContextFlight.java
> +
noted, will retain start-stop

2023-04-05 19:52 UTC, dexamundsen commented on service/src/main/java/bio/terra/workspace/service/workspace/flight/WorkspaceFlightMapKeys.java
> +    public static final String CREATE_AWS_CLOUD_CONTEXT_FLIGHT_ID = "createAwsCloudContextFlightId";
This is not needed until Clone is implemented. Removed

2023-04-05 23:36 UTC, dexamundsen commented on service/src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
> +        .addParameter(WorkspaceFlightMapKeys.WORKSPACE_ID, workspace.getWorkspaceId().toString())
removed, since function jobBuilder.populateInputParams adds this internally

2023-04-06 00:23 UTC, dexamundsen commented on service/src/main/java/bio/terra/workspace/service/workspace/AwsCloudContextService.java
> +          AwsUtils.createEnvironmentDiscovery(awsConfiguration).discoverEnvironment();
Made changes. This was each cloud context request shall discover the environment. 
Similarly each resource request shall fetch the landing zone (not implemented in this changeset)

2023-04-06 16:47 UTC, dexamundsen commented
> Thanks for addressing my comments! Not sure if there are tests still to come, but product code LGTM.

I have a PR for tests in the works, plan to get that completed today

2023-04-06 17:47 UTC, ddietterich commented on service/src/main/java/bio/terra/workspace/service/workspace/AwsCloudContextService.java
> +  public void createAwsCloudContextStart(UUID workspaceUuid, String flightId) {
I'd say leave it as is.

2023-04-06 17:48 UTC, ddietterich approved these changes

2023-04-06 17:51 UTC, dexamundsen commented
Tests added in https://github.com/DataBiosphere/terra-workspace-manager/pull/1189

2023-04-06 20:34 UTC, zloery commented on service/src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
> +  public void deleteAwsCloudContext(Workspace workspace, AuthenticatedUserRequest userRequest) {
My main concern was whether this function would work with AWS disabled - presumably, that would also mean other AWS configuration (discovery settings, etc.) are unavailable.
Given that a context is just a WSM db record and doesn't exist in the backing infra I think it's possible to run the delete with AWS disabled, but I'd prefer including the check anyways

2023-04-06 20:34 UTC, zloery approved these changes

2023-04-06 22:23 UTC, merged