Fix bigquery data transfer test
DataBiosphere/terra-workspace-manager pull request #1233
Opened 2023-04-28 14:46 UTC by yuhuyoyo

The pet SA is missing the permissions of the service account token creator role. I manually tested by adding these permissions into the PROJECT_OWNER role. It took a few min for the permissions to be synced to the actual pet SA but it works.

2023-04-28 16:45 UTC, zloery requested changes
The given error message is that a service agent (GCP managed SA) is missing permission on the pet SA, but this change (and your manual testing one) are giving additional permissions to the user and pet, so I'm not sure how that helped.

Running locally I also see the tests pass with just the retry changes from this PR, so maybe this was actually a permissions delay issue with a misleading error message all along 🤷

2023-04-28 16:45 UTC, zloery commented on service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/CustomGcpIamRoleMapping.java
> +          "iam.serviceAccounts.getAccessToken",
This block of permissions is granted on a BQ dataset, I don't think the SA related ones will have any effect here

2023-04-28 17:48 UTC, zloery approved these changes

2023-05-01 13:47 UTC, ddietterich approved these changes

2023-05-01 13:48 UTC, merged