[PF-2776] - Add hail install script to cluster startup script
DataBiosphere/terra-workspace-manager pull request #1449
Opened 2023-08-24 14:28 UTC by rogerwangcs

This changes adds a section to the dataproc cluster startup script that creates a python hail installation script and 

Notes:
- This startup script executes before dataproc installs its optional components onto the cluster. The hail scripts breaks the dataproc install scripts causing the cluster to report an error status. Therefore we poll for the dataproc component gateway service to become active before executing the hail script.
- I've tried creating a separate hail systemd service that is configured to run after the component gateway service, but I don't think its possible to create a systemd unit during startup trigger it to execute at the correct time without doing a reboot.

2023-08-24 17:47 UTC, mbookman requested changes

2023-08-24 17:47 UTC, mbookman commented on service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/dataproccluster/startup.sh
> +def mkdir_if_not_exists(path):
This wrapper function feels low-value. Would recommend calling os.makedirs(...) directly.

2023-08-24 17:47 UTC, mbookman commented on service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/dataproccluster/startup.sh
> +command = ['${MINICONDA_BIN}pip', 'install']
Recommend:

```
command = ['${RUN_PIP}', 'install'] + pip_pkgs
```

2023-08-24 17:47 UTC, mbookman commented on service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/dataproccluster/startup.sh
> +print("hail installed successfully.")
Would be nice to have an emit function:

```
import datetime
import sys

def emit(msg):
    print(f"{datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')} {msg}")
```

2023-08-24 17:47 UTC, mbookman commented on service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/dataproccluster/startup.sh
> +# Restart jupyter service
Remove this?

2023-08-24 17:47 UTC, mbookman commented on service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/dataproccluster/startup.sh
> +spark_monitor_gs = 'gs://hail-common/sparkmonitor-3b2bc8c22921f5c920fc7370f3a160d820db1f51/sparkmonitor-0.0.11-py3-none-any.whl'
Upper-case the module globals:

```
SPARK_MONITOR_GS = ...
SPARK_MONITOR_WHEEL = 
```

This block could use some comments.

2023-08-24 17:47 UTC, mbookman commented on service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/dataproccluster/startup.sh
> +  # Fork the following into background process to wait for dataproc to finish installing optional components including jupyter and start the proxy gateway service. Then safely install hail.
Break this long comment into multiple lines

2023-08-24 18:14 UTC, rogerwangcs commented on service/src/main/java/bio/terra/workspace/service/resource/controlled/cloud/gcp/dataproccluster/startup.sh
> +readonly MINICONDA_BIN="/opt/conda/miniconda3/bin/"
I see, that makes sense, I'll go ahead and define a variable for each of them.

2023-08-24 18:20 UTC, rogerwangcs commented
@mbookman Thanks for the quick review! Regarding your comments on the python script portion of this change: I didn't want to do more than the minimum change needed from the hail provided `init_notebook.py`. So I didn't touch any part of their script apart from removing a few conflicting/overlapping packages and a code block that starts up a jupyter service. Perhaps I can note in comment the change I made to the script to make this clearer?

2023-08-24 18:31 UTC, mbookman commented
> I didn't want to do more than the minimum change needed from the hail provided init_notebook.py

That makes total sense. Making that very clear in the code would be good.

2023-08-25 00:31 UTC, mbookman approved these changes
Just a few nits, but otherwise LGTM.

2023-08-25 15:14 UTC, cbookg approved these changes

2023-08-25 15:32 UTC, merged