[PF-1753] Add highest role to workspace returned by workspace actions
DataBiosphere/terra-workspace-manager pull request #694
Opened 2022-06-25 01:17 UTC by melissachang

ListWorkspaces works in swagger:

![image](https://user-images.githubusercontent.com/10929390/175752648-340a81ae-b076-454f-9326-b57928f36003.png)

Also tested in swagger: GetWorkspace, GetWorkspaceByUserFacingId, UpdateWorkspace

FYI there was one test where workspace had APPLICATION role: [PrivateResourceCleanupServiceTest. cleanupResourcesSuppressExceptions_cleansApplicationPrivateResource_succeeds()](https://github.com/DataBiosphere/terra-workspace-manager/blob/ff8d0ac9e043ff58e97afb68faf5a1836d1c7685/service/src/test/java/bio/terra/workspace/service/privateresource/PrivateResourceCleanupServiceTest.java#L239)

2022-06-28 14:17 UTC, cbookg commented on openapi/src/parts/workspace.yaml
> +        highestRole:
should this be required?

2022-06-28 14:18 UTC, ddietterich requested changes
I do not think the highestRole should be in the workspace object. Ideally, that object is not mutated after being fetched from the DB. Instead, I think highest role should only be fetched from the controller when we need to return the data to the caller. We never use it internally to WSM.

2022-06-28 14:18 UTC, ddietterich commented on service/src/main/java/bio/terra/workspace/service/iam/model/WsmIamRole.java
> +      Preconditions.checkState(
Why do we need to require that an application only have APPLICATION role?
I think you get the same effect if you decide that APPLICATION collates highest.

2022-06-28 23:34 UTC, melissachang commented on service/src/main/java/bio/terra/workspace/service/iam/SamService.java
> +   * @return
Done

2022-06-29 15:54 UTC, ddietterich approved these changes
LGTM, thank you!

2022-06-29 15:57 UTC, ddietterich commented on service/src/main/java/bio/terra/workspace/service/workspace/WorkspaceService.java
> +
I wish the layering was cleaner between service and controller. We end up with more controller code than I would like; especially in the resource methods. The benefit is that the resource objects are immutable.

2022-06-29 20:09 UTC, yuhuyoyo approved these changes

2022-06-29 21:02 UTC, melissachang commented on openapi/src/parts/workspace.yaml
> +            Highest role. If requester is both reader and writer, writer will be
Done

2022-06-29 21:02 UTC, melissachang commented on service/src/main/java/bio/terra/workspace/service/iam/model/WsmIamRole.java
> +    } else if (roles.contains(WsmIamRole.OWNER)) {
`else if` after `return` looks pretty common, so I'll leave as is -- It's a little more clear to me (though you're right that the `else` doesn't do anything).

https://cs.github.com/DataBiosphere/terra-workspace-manager?q=return+%22else+if%22

2022-06-29 22:03 UTC, merged