Mikenev/pf 1085
DataBiosphere/terra-workspace-manager pull request #720
Opened 2022-07-12 21:23 UTC by mikenev

Just a draft

2022-07-14 20:52 UTC, yuhuyoyo approved these changes

2022-07-14 20:53 UTC, yuhuyoyo commented
can you update the PR name to be more descriptive

2022-07-14 21:06 UTC, zloery approved these changes

2022-07-14 21:13 UTC, ddietterich requested changes
One suggested change and one maybe...

2022-07-14 21:42 UTC, mikenev commented on service/src/main/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiController.java
> +                  .getOrDefault(WorkspaceConstants.Properties.DEFAULT_RESOURCE_LOCATION, null));
I was considering pulling the code into a shared fragment, so I'll do that next.

Filling the fallback location here makes sense too. Does that mean we make location a required field and don't fill it in at the service layer? That seems to make sense. Tests would all need to be updated for that, which is fine.

2022-07-14 21:45 UTC, ddietterich commented on service/src/main/java/bio/terra/workspace/app/controller/ControlledGcpResourceApiController.java
> +                  .getOrDefault(WorkspaceConstants.Properties.DEFAULT_RESOURCE_LOCATION, null));
I was thinking that we would always fill location in here, so it would never be null. Good thought about the tests; they would need to be updated.

2022-07-15 16:01 UTC, ddietterich approved these changes
lgtm - thanks!

2022-07-16 11:26 UTC, merged